### ISSUE TITLE
Feature request: add mingwX86 as a target

### ISSUE THREAD

**Issue by JohnLCaron** [Kotlin/kotlinx-datetime#224]
Would it be possible to add mingwX86() as a target?

**Comment by dkhalanskyjb** [comment]
A tricky question. The answer is the same as for https://github.com/Kotlin/kotlinx-datetime/issues/75: *maybe* it already works and it's enough to just enable the target in the project config, like so:
```patch
From f3d902a5a799408854e54d0338335dda0bd874fa Mon Sep 17 00:00:00 2001
From: Dmitry Khalanskiy <Dmitry.Khalanskiy@jetbrains.com>
Date: Wed, 7 Sep 2022 11:01:33 +0200
Subject: [PATCH] Add mingwX86 to the list of targets

---
 core/build.gradle.kts          | 1 +
 serialization/build.gradle.kts | 1 +
 2 files changed, 2 insertions(+)

diff --git a/core/build.gradle.kts b/core/build.gradle.kts
index 180fcbc..d05544d 100644
--- a/core/build.gradle.kts
+++ b/core/build.gradle.kts
@@ -37,6 +37,7 @@ kotlin {
     infra {
         target("linuxX64")
         target("mingwX64")
+        target("mingwX32")
 
         common("darwin") {
             target("macosX64")
diff --git a/serialization/build.gradle.kts b/serialization/build.gradle.kts
index 91a5c4e..c9950c8 100644
--- a/serialization/build.gradle.kts
+++ b/serialization/build.gradle.kts
@@ -16,6 +16,7 @@ kotlin {
     infra {
         target("linuxX64")
         target("mingwX64")
+        target("mingwX86")
         target("macosX64")
         target("macosArm64")
         target("iosX64")
-- 
2.30.2
```

We don't know because we don't have a machine to test this on. You could clone our repository, modify the project to also build for mingwX86, and see if it works. We won't do that until there's a way to test the code and/or a policy regarding how well our libraries should be tested on different platforms.

**Comment by dkhalanskyjb** [comment]
Kotlin/Native itself stops support for this target: https://kotlinlang.org/docs/native-target-support.html#deprecated-targets Nothing can be done on this library's side, sorry.
