### ISSUE TITLE
`Duration.ofUnit()` equivalent (from java.time)

### ISSUE THREAD

**Issue by wiryadev** [Kotlin/kotlinx-datetime#241]
My usecase is i want to get remaining time from epochSeconds. Currently, as far as i know, we can only get one of it (either hours only or minutes only for example). I want to get the whole duration and take its unit part like what `java.time` does (in below example is `duration.toHoursPart()`).

For now, i have to use both kotlinx.datetime and java.time to achieve this conveniently. Here is what my usage looks like:

```
// kind of util function
fun timeDiff(
    targetTime: Instant,
    currentTime: Instant = Clock.System.now(),
): LocalTime {
    val diff = currentTime.until(targetTime, DateTimeUnit.SECOND)
    val duration = Duration.ofSeconds(diff) // duration from java.time

    return LocalTime(hour = duration.toHoursPart(), minute = duration.toMinutesPart())
}

// how i use this
fun main(args: Array<String>) {
    val localTime = "04:36".toLocalTime()
    val target: Instant = localTime
        .atDate(year = 2022, monthNumber = 11, dayOfMonth = 2)
        .toInstant(TimeZone.currentSystemDefault())

    val timeLeft = timeDiff(targetTime = target)
    println("${timeLeft.hour}h ${timeLeft.minute}mins to go")
}

// output
8h 46mins to go
```

**Comment by ilya-g** [comment]
I believe this question is not related to this library, because the `Duration` type is provided by the Kotlin standard library.

Nevertheless, if you have a `Duration` value that represents the difference between two instants, you can split it into components with [toComponents](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/to-components.html) function. Choose the overload that accepts lambda starting with hours component:
```
val diff: Duration = ...
diff.toComponents { hours, minutes, _, _ ->
    println("${hours}h ${minutes}min to go")
}
```
