### ISSUE TITLE
`String.toInstant` throws exception on macosx64, but not jvm

### ISSUE THREAD

**Issue by 05nelsonm** [Kotlin/kotlinx-datetime#269]
Got a `DateTimeFormatException` when converting a string value which was produced on `jvm`. to an `Instant` on `macosx64`

```kotlin
// jvm

val instantString = Clock.System.now().plus(Int.MAX_VALUE.days).toString()
instantString.toInstant() // << does not throw

println(instantString)
// +5881633-11-04T10:51:10.025414219Z
```

```kotlin
// macosx64
"+5881633-11-04T10:51:10.025414219Z".toInstant() // << throws DateTimeFormatException
```

**Comment by dkhalanskyjb** [comment]
Native and JS support a much smaller range of years than JVM, namely years ±1000000 at most, instead of ±1000000000 for the JVM. We didn't consider dates outside the smaller range to be useful in practice.

The only values that are guaranteed to work across all platforms are those between `Instant.DISTANT_PAST` and `Instant.DISTANT_FUTURE`.

**Comment by 05nelsonm** [comment]
Yes, that is what I ended up using in the event the addition operation exceeded `Instant.DISTANT_FUTURE` on jvm so that conversion on `macosx64` works.

I see now it *is* documented on [Instant.DISTANT_FUTURE](https://github.com/Kotlin/kotlinx-datetime/blob/5a737823262ff96c14585bf868cefcc5016c80ea/core/common/src/Instant.kt#L192), will close this issue as it's "expected" behavior.
