### ISSUE TITLE
Support Kotlin 2.0

### ISSUE THREAD

**Issue by egorikftp** [Kotlin/kotlinx-datetime#445]
We have started migration our kmp infrastructure on Kotlin 2.0 and faced binary compatibility lint checks in `kotlin-datetime` library.

```kotlin
/kotlinx-datetime-jvm-0.6.1.jar!/META-INF/kotlinx-datetime.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
```

**Comment by egorikftp** [comment]
https://github.com/Kotlin/kotlinx-datetime/pull/446

**Comment by JakeWharton** [comment]
That error message is actually telling you the opposite. It's saying that the tool attempting to consume the metadata of this library can only parse up to Kotlin 1.7.x, whereas datetime was built with 1.9.x.

If I had to guess, it's probably an old version of Gradle which embeds (really) old versions of Kotlin, historically.

Upgrading Kotlin in this library and getting a new release will only change that error message to say "2.0.0" instead of "1.9.0" when referencing the library's binary metadata version.

**Comment by dkhalanskyjb** [comment]
Yep, Kotlin 2.0 should work fine with `kotlinx-datetime` 0.6.1.
