### ISSUE TITLE
Instant <> LocalDateTime conversion and DST

### ISSUE THREAD

**Issue by matejdro** [Kotlin/kotlinx-datetime#59]
This is mostly a question, after seeing the talk at 1.4 event: https://youtu.be/YwN0kAMNvXI?t=475

Considering that library already knows that user's selected zone is Berlin (and we can know when DST starts and stops in Berlin), shouldn't exact conversion of that be possible?

**Comment by dennis-kuypers-gcx** [comment]
I think he talks about discontinuity of local date time.

Here's a google talk about cctz a C++ date time library. They have a very nice graphic to show what happens when you have DST jumps and how it affects Instant to DateTime conversions. (at 26m 47s)

https://www.youtube.com/watch?v=2rnIHsqABfM&t=26m47s

**Comment by ilya-g** [comment]
Nice explanation!

**Comment by matejdro** [comment]
I see, I thought that the problem was for the entire half of the year when DST is in effect, but now I see that the issue is only for that one hour when DST shifts.

Thanks for that explanation video, it was really helpful. Closing down this since it was answered.
