### ISSUE TITLE
Provide constructor for Instant class that takes a Double

### ISSUE THREAD

**Issue by ta834n** [Kotlin/kotlinx-datetime#77]
Hello,
I really like using your project. I just miss one little feature:
could you provide a constructor for the Instant class that takes a timestamp of type Double (milliseconds since 1 January 1970 UTC)?

Reason: we try to avoid creating objects in our multi-platform project wherever possible, but using Long for timestamps results in object creation. A Double value can be directly mapped to a JavaScript Number value. It also feels more natural to what the JavaScript Date class does.

Thanks in advance!

**Comment by Jadarma** [comment]
The `Instant` class itself is written with discrete units in mind, since they are faster to do calculations with and easier to reason about on platforms that have the concept of longs (all targets except JS). Internally, all instants hold their data as a `Long`, so even if a constructor would accept a double, in order to adapt it to the common definition, it will still have to do the conversion, introducing the boxing. The only alternative would be to rewrite the JS implementation to not use longs at all, which is not an option since it would make it too different from the others, so this object creation in JavaScript is a necessary evil that shouldn't be circumvented.

I would instead suggest you define your own constructor by extending the companion object, just so at least you don't have to put a `.toLong()` in every place where it is called:

```kotlin
@Suppress("NOTHING_TO_INLINE")
inline fun Instant.Companion.fromEpochMilliseconds(epochMilliseconds: Double) =
    Instant.fromEpochMilliseconds(epochMilliseconds.toLong())

val time = Instant.fromEpochMilliseconds(12345678.9)
```

The real question is: have you noticed any significant performance issues in your project while using the library?
If so, are you sure it is related to the boxing?

**Comment by ta834n** [comment]
Hello @Jadarma ,
thank you very much for that answer.
To answer your question: I have not checked whether there are performance issues while using the library.
We have heavily used timestamps of type Long in our project but replaced them all with Double values once we measured an performance impact. As far as I know only Int values are mapped to JavaScript Number values but they cannot be used due to their reduced range.
Since we do not want to go back to Long values I have to reevaluate for which part I will use kotlinx-datetime.

**Comment by Jadarma** [comment]
Hello, @ta834n. Glad I could help. Just a small correction: all numeric types except `Long` are mapped to the JS `Number`, see [here](https://kotlinlang.org/docs/reference/js-to-kotlin-interop.html#representing-kotlin-types-in-javascript).
